[package]
name = "engine-3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
pixels_primitives = "0.1.1"
winit = "0.28.6"
winit_input_helper = "0.14.1"
